-- 가상조달기관 레거시 DB (pps_legacy) — 시연용 가상 데이터
-- 2000~2010년대 공공 운영 DB 에서 흔한 모습을 일부러 재현한다.
--   · FK 를 선언하지 않는다 (이관·성능 편의로 빼 두는 관행) → 관계는 컬럼 이름으로만 추측할 수 있다
--   · 일자·일시는 CHAR(8)/CHAR(12) 문자열, 일부 금액은 VARCHAR (천 단위 쉼표가 섞인다)
--   · 삭제하지 않고 USE_YN 으로 숨긴다, 변경 이력은 같은 테이블에 차수 행으로 쌓인다
--   · 코드값의 이름은 TB_CMMN_CD 한 곳에 몰려 있다
-- 열 이름은 공공데이터 공통표준용어식 약어(…_NO, …_NM, …_CD, …_YMD, …_AMT)를 쓴다.

DROP TABLE IF EXISTS TB_BID_NTCE, TB_OPNG_RSLT, TB_CNTRCT, TB_PRDCT_CLSFC, TB_PRDCT_IDNT, TB_DMINSTT,
  TB_ENTRPS, TB_DLVR_REQ, TB_PYMNT, TB_CMMN_CD, TB_STCK;

CREATE TABLE TB_DMINSTT (
  DMINSTT_CD   CHAR(7)      PRIMARY KEY,
  DMINSTT_NM   VARCHAR(100) NOT NULL,
  INSTT_TY_NM  VARCHAR(50)
);
COMMENT ON TABLE TB_DMINSTT IS '수요기관';

CREATE TABLE TB_ENTRPS (
  BIZRNO        VARCHAR(12)  PRIMARY KEY,   -- 하이픈 포함으로 저장된 레거시 습관
  CORP_NM       VARCHAR(100) NOT NULL,
  RPRSV_NM      VARCHAR(50),               -- 개인정보: 대표자명
  RGN_NM        VARCHAR(50),
  TELNO         VARCHAR(20),               -- 개인정보: 전화
  ENTRPS_DIV_NM VARCHAR(20)
);
COMMENT ON TABLE TB_ENTRPS IS '조달업체';

CREATE TABLE TB_PRDCT_CLSFC (
  DTIL_PRDCT_CLSFC_NO CHAR(10)    PRIMARY KEY,
  PRDCT_CLSFC_NO      CHAR(8)     NOT NULL,
  DTIL_PRDCT_CLSFC_NM VARCHAR(100),
  UNIT_NM             VARCHAR(20)
);
COMMENT ON TABLE TB_PRDCT_CLSFC IS '물품분류(세부품명). 분류번호 8자리 + 2자리';

CREATE TABLE TB_PRDCT_IDNT (
  PRDCT_IDNT_NO       CHAR(8)     PRIMARY KEY,
  DTIL_PRDCT_CLSFC_NO CHAR(10),
  MODEL_NM            VARCHAR(100),
  MAKER_BIZRNO        VARCHAR(12),
  UNIT_PRCE           NUMERIC(15)
);
COMMENT ON TABLE TB_PRDCT_IDNT IS '물품식별(제조사·모델별 8자리)';

CREATE TABLE TB_BID_NTCE (
  BID_NTCE_NO         VARCHAR(13) NOT NULL,
  BID_NTCE_ORD        CHAR(3)     NOT NULL,
  BID_NTCE_NM         VARCHAR(300),
  NTCE_KIND_NM        VARCHAR(20),
  NTCE_INSTT_CD       CHAR(7),
  DMINSTT_CD          CHAR(7),
  BID_NTCE_DT         CHAR(12),
  BID_CLSE_DT         CHAR(12),
  OPENG_DT            CHAR(12),
  PRESMPT_PRCE        NUMERIC(15),
  ASIGN_BDGT_AMT      VARCHAR(20),    -- 숫자가 아니라 문자열로 들어간 금액
  CNTRCT_CNCLS_MTHD_NM VARCHAR(30),
  DTIL_PRDCT_CLSFC_NO CHAR(10),
  PRDCT_QTY           NUMERIC(12),
  PRDCT_UNIT          VARCHAR(10),
  PRIMARY KEY (BID_NTCE_NO, BID_NTCE_ORD)
);
COMMENT ON TABLE TB_BID_NTCE IS '입찰공고 (공고번호+차수)';
CREATE INDEX IX_BID_NTCE_01 ON TB_BID_NTCE (BID_NTCE_DT);
CREATE INDEX IX_BID_NTCE_02 ON TB_BID_NTCE (DMINSTT_CD);

CREATE TABLE TB_OPNG_RSLT (
  BID_NTCE_NO     VARCHAR(13) NOT NULL,
  BID_NTCE_ORD    CHAR(3)     NOT NULL,
  OPENG_DT        CHAR(12),
  PRTCPT_CNUM     NUMERIC(5),
  BIDWINNR_BIZRNO VARCHAR(12),
  BIDWINNR_NM     VARCHAR(100),
  SUCSFBID_AMT    VARCHAR(20),
  SUCSFBID_RATE   NUMERIC(7,3),
  PRIMARY KEY (BID_NTCE_NO, BID_NTCE_ORD)
);
COMMENT ON TABLE TB_OPNG_RSLT IS '개찰결과·낙찰';

CREATE TABLE TB_CNTRCT (
  DCSN_CNTRCT_NO   CHAR(13)    NOT NULL,   -- 확정계약번호 앞 13자리, 차수는 CHG_ORD
  CHG_ORD          CHAR(2)     NOT NULL,
  UNTY_CNTRCT_NO   CHAR(13),
  CNTRCT_NM        VARCHAR(300),
  CNTRCT_CNCLS_YMD CHAR(8),
  CNTRCT_AMT       NUMERIC(15),
  DMINSTT_CD       CHAR(7),
  BIZRNO           VARCHAR(12),
  BID_NTCE_NO      VARCHAR(13),
  DLVR_TMLMT_YMD   CHAR(8),
  PRIMARY KEY (DCSN_CNTRCT_NO, CHG_ORD)
);
COMMENT ON TABLE TB_CNTRCT IS '계약. 변경 시 같은 번호의 차수 행이 추가된다';

CREATE TABLE TB_DLVR_REQ (
  DLVR_REQ_NO   VARCHAR(12) PRIMARY KEY,
  DLVR_REQ_YMD  CHAR(8),
  DMINSTT_CD    CHAR(7),
  PRDCT_IDNT_NO CHAR(8),
  BIZRNO        VARCHAR(12),
  DLVR_REQ_QTY  NUMERIC(10),
  UNIT_PRCE     NUMERIC(15),
  DLVR_REQ_AMT  NUMERIC(15),
  DLVR_STTS_CD  CHAR(2),
  USE_YN        CHAR(1) DEFAULT 'Y'
);
COMMENT ON TABLE TB_DLVR_REQ IS '쇼핑몰형 납품요구';

CREATE TABLE TB_PYMNT (
  PYMNT_REQ_NO  VARCHAR(12) PRIMARY KEY,
  REF_SE        CHAR(1),                -- C 계약 / D 납품요구
  REF_NO        VARCHAR(15),
  DMINSTT_CD    CHAR(7),
  BIZRNO        VARCHAR(12),
  REQ_YMD       CHAR(8),
  REQ_AMT       VARCHAR(20),            -- '1,234,000' 형태
  PYMNT_STTS_CD CHAR(2),
  PYMNT_YMD     CHAR(8),
  ACNT_DIV_CD   CHAR(2),                -- DB 에는 있다. FINL API 는 돌려주지 않는다
  BDGT_ACNT_NM  VARCHAR(30)
);
COMMENT ON TABLE TB_PYMNT IS '대금 청구·지급';

CREATE TABLE TB_CMMN_CD (
  CD_ID  VARCHAR(20) NOT NULL,
  CD     VARCHAR(10) NOT NULL,
  CD_NM  VARCHAR(100),
  USE_YN CHAR(1) DEFAULT 'Y',
  PRIMARY KEY (CD_ID, CD)
);
COMMENT ON TABLE TB_CMMN_CD IS '공통코드';

CREATE TABLE TB_STCK (
  ITEM_CD   VARCHAR(5)  NOT NULL,
  SITE_CD   VARCHAR(5)  NOT NULL,
  ITEM_NM   VARCHAR(50),
  SITE_NM   VARCHAR(50),
  STOCK_QTY NUMERIC(10,1),
  UNIT_NM   VARCHAR(10),
  BASE_YMD  CHAR(8),
  PRIMARY KEY (ITEM_CD, SITE_CD)
);
COMMENT ON TABLE TB_STCK IS '비축물자 재고';
